package bhg.sucks.model;

import bhg.sucks.R;

public enum Skill {

    EnemyDefenderSpawnTime(Category.Weapon, R.string.EnemyDefenderSpawnTime, Bonus.POS),
    DefenderSpawnTime(Category.Weapon, R.string.DefenderSpawnTime, Bonus.NEG),
    HeavyInfantryHitpoints(Category.Weapon, R.string.HeavyInfantryHitpoints, Bonus.POS),
    RangedInfantryHitpoints(Category.Weapon, R.string.RangedInfantryHitpoints, Bonus.POS),
    HeavyCavalryHitpoints(Category.Weapon, R.string.HeavyCavalryHitpoints, Bonus.POS),
    RaiderHitpoints(Category.Weapon, R.string.RaiderHitpoints, Bonus.POS),
    WallSapperHitpoints(Category.Weapon, R.string.WallSapperHitpoints, Bonus.POS),
    SupplyVehicleHitpoints(Category.Weapon, R.string.SupplyVehicleHitpoints, Bonus.POS),
    RangedSiegeHitpoints(Category.Weapon, R.string.RangedSiegeHitpoints, Bonus.POS),
    MortarTroopHitpoints(Category.Weapon, R.string.MortarTroopHitpoints, Bonus.POS),
    AttackHelicoptersHitpoints(Category.Weapon, R.string.AttackHelicoptersHitpoints, Bonus.POS),
    MachineGunInfantryHitpoints(Category.Weapon, R.string.MachineGunInfantryHitpoints, Bonus.POS),
    GuerrillaHitpoints(Category.Weapon, R.string.GuerrillaHitpoints, Bonus.POS),
    HeavyTankHitpoints(Category.Weapon, R.string.HeavyTankHitpoints, Bonus.POS),
    BazookaHitpoints(Category.Weapon, R.string.BazookaHitpoints, Bonus.POS),
    APCHitpoints(Category.Weapon, R.string.APCHitpoints, Bonus.POS),
    ArmoredCarHitpoints(Category.Weapon, R.string.ArmoredCarHitpoints, Bonus.POS),
    TacticalHelicopterHitpoints(Category.Weapon, R.string.TacticalHelicopterHitpoints, Bonus.POS),
    MRLHitpoints(Category.Weapon, R.string.MRLHitpoints, Bonus.POS),
    FighterHitpoints(Category.Weapon, R.string.FighterHitpoints, Bonus.POS),
    BomberHitpoints(Category.Weapon, R.string.BomberHitpoints, Bonus.POS),
    ParatroopersFromTransportsHitpoints(Category.Weapon, R.string.ParatroopersFromTransportsHitpoints, Bonus.POS),
    GeneralsHitpoints(Category.Weapon, R.string.GeneralsHitpoints, Bonus.POS),
    HeavyInfantryDamage(Category.Weapon, R.string.HeavyInfantryDamage, Bonus.POS),
    RangedInfantryDamage(Category.Weapon, R.string.RangedInfantryDamage, Bonus.POS),
    HeavyCavalryDamage(Category.Weapon, R.string.HeavyCavalryDamage, Bonus.POS),
    RaiderDamage(Category.Weapon, R.string.RaiderDamage, Bonus.POS),
    WallSapperDamage(Category.Weapon, R.string.WallSapperDamage, Bonus.POS),
    SupplyVehicleHealing(Category.Weapon, R.string.SupplyVehicleHealing, Bonus.POS),
    RangedSiegeDamage(Category.Weapon, R.string.RangedSiegeDamage, Bonus.POS),
    MortarTroopDamage(Category.Weapon, R.string.MortarTroopDamage, Bonus.POS),
    AttackHelicoptersDamage(Category.Weapon, R.string.AttackHelicoptersDamage, Bonus.POS),
    MachineGunInfantryDamage(Category.Weapon, R.string.MachineGunInfantryDamage, Bonus.POS),
    GuerrillaDamage(Category.Weapon, R.string.GuerrillaDamage, Bonus.POS),
    HeavyTankDamage(Category.Weapon, R.string.HeavyTankDamage, Bonus.POS),
    BazookaDamage(Category.Weapon, R.string.BazookaDamage, Bonus.POS),
    APCDamage(Category.Weapon, R.string.APCDamage, Bonus.POS),
    ArmoredCarDamage(Category.Weapon, R.string.ArmoredCarDamage, Bonus.POS),
    TacticalHelicopterHealing(Category.Weapon, R.string.TacticalHelicopterHealing, Bonus.POS),
    MRLDamage(Category.Weapon, R.string.MRLDamage, Bonus.POS),
    FighterDamage(Category.Weapon, R.string.FighterDamage, Bonus.POS),
    BomberDamage(Category.Weapon, R.string.BomberDamage, Bonus.POS),
    ParatroopersFromTransportsDamage(Category.Weapon, R.string.ParatroopersFromTransportsDamage, Bonus.POS),
    GeneralsDamage(Category.Weapon, R.string.GeneralsDamage, Bonus.POS),

    DefenderHitpoints(Category.Armor, R.string.DefenderHitpoints, Bonus.POS),
    DefenderDamage(Category.Armor, R.string.DefenderDamage, Bonus.POS),
    InvadingHeavyInfantryHitpoints(Category.Armor, R.string.InvadingHeavyInfantryHitpoints, Bonus.NEG),
    InvadingRangedInfantryHitpoints(Category.Armor, R.string.InvadingRangedInfantryHitpoints, Bonus.NEG),
    InvadingHeavyCavalryHitpoints(Category.Armor, R.string.InvadingHeavyCavalryHitpoints, Bonus.NEG),
    InvadingRaiderHitpoints(Category.Armor, R.string.InvadingRaiderHitpoints, Bonus.NEG),
    InvadingWallSapperHitpoints(Category.Armor, R.string.InvadingWallSapperHitpoints, Bonus.NEG),
    InvadingSupplyVehicleHitpoints(Category.Armor, R.string.InvadingSupplyVehicleHitpoints, Bonus.NEG),
    InvadingRangedSiegeHitpoints(Category.Armor, R.string.InvadingRangedSiegeHitpoints, Bonus.NEG),
    InvadingMortarTroopHitpoints(Category.Armor, R.string.InvadingMortarTroopHitpoints, Bonus.NEG),
    InvadingAttackHelicoptersHitpoints(Category.Armor, R.string.InvadingAttackHelicoptersHitpoints, Bonus.NEG),
    InvadingMachineGunInfantryHitpoints(Category.Armor, R.string.InvadingMachineGunInfantryHitpoints, Bonus.NEG),
    InvadingGuerrillaHitpoints(Category.Armor, R.string.InvadingGuerrillaHitpoints, Bonus.NEG),
    InvadingHeavyTankHitpoints(Category.Armor, R.string.InvadingHeavyTankHitpoints, Bonus.NEG),
    InvadingBazookaHitpoints(Category.Armor, R.string.InvadingBazookaHitpoints, Bonus.NEG),
    InvadingAPCHitpoints(Category.Armor, R.string.InvadingAPCHitpoints, Bonus.NEG),
    InvadingArmoredCarHitpoints(Category.Armor, R.string.InvadingArmoredCarHitpoints, Bonus.NEG),
    InvadingTacticalHelicopterHitpoints(Category.Armor, R.string.InvadingTacticalHelicopterHitpoints, Bonus.NEG),
    InvadingMRLHitpoints(Category.Armor, R.string.InvadingMRLHitpoints, Bonus.NEG),
    InvadingFighterHitpoints(Category.Armor, R.string.InvadingFighterHitpoints, Bonus.NEG),
    InvadingBomberHitpoints(Category.Armor, R.string.InvadingBomberHitpoints, Bonus.NEG),
    InvadingParatroopersFromTransportsHitpoints(Category.Armor, R.string.InvadingParatroopersFromTransportsHitpoints, Bonus.NEG),
    InvadingGeneralsHitpoints(Category.Armor, R.string.InvadingGeneralsHitpoints, Bonus.NEG),
    InvadingHeavyInfantryDamage(Category.Armor, R.string.InvadingHeavyInfantryDamage, Bonus.NEG),
    InvadingRangedInfantryDamage(Category.Armor, R.string.InvadingRangedInfantryDamage, Bonus.NEG),
    InvadingHeavyCavalryDamage(Category.Armor, R.string.InvadingHeavyCavalryDamage, Bonus.NEG),
    InvadingRaiderDamage(Category.Armor, R.string.InvadingRaiderDamage, Bonus.NEG),
    InvadingWallSapperDamage(Category.Armor, R.string.InvadingWallSapperDamage, Bonus.NEG),
    InvadingSupplyVehicleHealing(Category.Armor, R.string.InvadingSupplyVehicleHealing, Bonus.NEG),
    InvadingRangedSiegeDamage(Category.Armor, R.string.InvadingRangedSiegeDamage, Bonus.NEG),
    InvadingMortarTroopDamage(Category.Armor, R.string.InvadingMortarTroopDamage, Bonus.NEG),
    InvadingAttackHelicoptersDamage(Category.Armor, R.string.InvadingAttackHelicoptersDamage, Bonus.NEG),
    InvadingMachineGunInfantryDamage(Category.Armor, R.string.InvadingMachineGunInfantryDamage, Bonus.NEG),
    InvadingGuerrillaDamage(Category.Armor, R.string.InvadingGuerrillaDamage, Bonus.NEG),
    InvadingHeavyTankDamage(Category.Armor, R.string.InvadingHeavyTankDamage, Bonus.NEG),
    InvadingBazookaDamage(Category.Armor, R.string.InvadingBazookaDamage, Bonus.NEG),
    InvadingAPCDamage(Category.Armor, R.string.InvadingAPCDamage, Bonus.NEG),
    InvadingArmoredCarDamage(Category.Armor, R.string.InvadingArmoredCarDamage, Bonus.NEG),
    InvadingTacticalHelicopterHealing(Category.Armor, R.string.InvadingTacticalHelicopterHealing, Bonus.NEG),
    InvadingMRLDamage(Category.Armor, R.string.InvadingMRLDamage, Bonus.NEG),
    InvadingFighterDamage(Category.Armor, R.string.InvadingFighterDamage, Bonus.NEG),
    InvadingBomberDamage(Category.Armor, R.string.InvadingBomberDamage, Bonus.NEG),
    InvadingParatroopersFromTransportsDamage(Category.Armor, R.string.InvadingParatroopersFromTransportsDamage, Bonus.NEG),
    InvadingGeneralsDamage(Category.Armor, R.string.InvadingGeneralsDamage, Bonus.NEG),

    OilLooted(Category.Jewelry, R.string.OilLooted, Bonus.POS),
    GoldLooted(Category.Jewelry, R.string.GoldLooted, Bonus.POS),
    FoodLooted(Category.Jewelry, R.string.FoodLooted, Bonus.POS),
    NationalTradeGoodLootChance(Category.Jewelry, R.string.NationalTradeGoodLootChance, Bonus.POS),
    AllResourceLooted(Category.Jewelry, R.string.AllResourceLooted, Bonus.POS),
    LootedResourceRefund(Category.Jewelry, R.string.LootedResourceRefund, Bonus.POS),
    LibraryTechGoldCost(Category.Jewelry, R.string.LibraryTechGoldCost, Bonus.NEG),
    EnemyTowerHitpoints(Category.Jewelry, R.string.EnemyTowerHitpoints, Bonus.NEG),
    EnemyCatapultHitpoints(Category.Jewelry, R.string.EnemyCatapultHitpoints, Bonus.NEG),
    EnemyAntiTankGunHitpoints(Category.Jewelry, R.string.EnemyAntiTankGunHitpoints, Bonus.NEG),
    EnemyRedoubtHitpoints(Category.Jewelry, R.string.EnemyRedoubtHitpoints, Bonus.NEG),
    EnemySniperTowerHitpoints(Category.Jewelry, R.string.EnemySniperTowerHitpoints, Bonus.NEG),
    EnemyAirDefenseHitpoints(Category.Jewelry, R.string.EnemyAirDefenseHitpoints, Bonus.NEG),
    EnemyMissileSiloHitpoints(Category.Jewelry, R.string.EnemyMissileSiloHitpoints, Bonus.NEG),
    EnemyTowerDamage(Category.Jewelry, R.string.EnemyTowerDamage, Bonus.NEG),
    EnemyCatapultDamage(Category.Jewelry, R.string.EnemyCatapultDamage, Bonus.NEG),
    EnemyAntiTankGunDamage(Category.Jewelry, R.string.EnemyAntiTankGunDamage, Bonus.NEG),
    EnemyRedoubtDamage(Category.Jewelry, R.string.EnemyRedoubtDamage, Bonus.NEG),
    EnemySniperTowerDamage(Category.Jewelry, R.string.EnemySniperTowerDamage, Bonus.NEG),
    EnemyAirDefenseDamage(Category.Jewelry, R.string.EnemyAirDefenseDamage, Bonus.NEG),
    EnemyMissileSiloDamage(Category.Jewelry, R.string.EnemyMissileSiloDamage, Bonus.NEG),

    GoldFromGoldMines(Category.Pottery, R.string.GoldFromGoldMines, Bonus.POS),
    FoodFromFruitTrees(Category.Pottery, R.string.FoodFromFruitTrees, Bonus.POS),
    AllResourcesFromHunting(Category.Pottery, R.string.AllResourcesFromHunting, Bonus.POS),
    GoldFromCaravans(Category.Pottery, R.string.GoldFromCaravans, Bonus.POS),
    FoodFromFarms(Category.Pottery, R.string.FoodFromFarms, Bonus.POS),
    OilFromOilWells(Category.Pottery, R.string.OilFromOilWells, Bonus.POS),
    VaultCapacity(Category.Pottery, R.string.VaultCapacity, Bonus.POS),
    VaultInterest(Category.Pottery, R.string.VaultInterest, Bonus.POS),
    ForestExpansionCostRefund(Category.Pottery, R.string.ForestExpansionCostRefund, Bonus.POS),
    LibraryTechFoodCost(Category.Pottery, R.string.LibraryTechFoodCost, Bonus.NEG),
    LibraryTechOilCost(Category.Pottery, R.string.LibraryTechOilCost, Bonus.NEG),
    TowerHitpoints(Category.Pottery, R.string.TowerHitpoints, Bonus.POS),
    CatapultHitpoints(Category.Pottery, R.string.CatapultHitpoints, Bonus.POS),
    AntiTankGunHitpoints(Category.Pottery, R.string.AntiTankGunHitpoints, Bonus.POS),
    RedoubtHitpoints(Category.Pottery, R.string.RedoubtHitpoints, Bonus.POS),
    SniperTowerHitpoints(Category.Pottery, R.string.SniperTowerHitpoints, Bonus.POS),
    AirDefenseHitpoints(Category.Pottery, R.string.AirDefenseHitpoints, Bonus.POS),
    MissileSiloHitpoints(Category.Pottery, R.string.MissileSiloHitpoints, Bonus.POS),
    TowerDamage(Category.Pottery, R.string.TowerDamage, Bonus.POS),
    CatapultDamage(Category.Pottery, R.string.CatapultDamage, Bonus.POS),
    AntiTankGunDamage(Category.Pottery, R.string.AntiTankGunDamage, Bonus.POS),
    RedoubtDamage(Category.Pottery, R.string.RedoubtDamage, Bonus.POS),
    SniperTowerDamage(Category.Pottery, R.string.SniperTowerDamage, Bonus.POS),
    AirDefenseDamage(Category.Pottery, R.string.AirDefenseDamage, Bonus.POS),
    MissileSiloDamage(Category.Pottery, R.string.MissileSiloDamage, Bonus.POS),

    WarFighterDamage(Category.WarWeapon, R.string.FighterDamage, Bonus.POS),
    WarBazookaDamage(Category.WarWeapon, R.string.BazookaDamage, Bonus.POS),
    WarHeavyTankDamage(Category.WarWeapon, R.string.HeavyTankDamage, Bonus.POS),
    WarGuerrillaDamage(Category.WarWeapon, R.string.GuerrillaDamage, Bonus.POS),
    WarInvadingHeavyTankHitpoints(Category.WarWeapon, R.string.InvadingHeavyTankHitpoints, Bonus.NEG),
    WarInvadingRangedSiegeHitpoints(Category.WarWeapon, R.string.InvadingRangedSiegeHitpoints, Bonus.NEG),
    WarAPCDamage(Category.WarWeapon, R.string.APCDamage, Bonus.POS),
    WarInvadingParatroopersFromTransportsHitpoints(Category.WarWeapon, R.string.InvadingParatroopersFromTransportsHitpoints, Bonus.NEG),
    WarInvadingGuerrillaHitpoints(Category.WarWeapon, R.string.InvadingGuerrillaHitpoints, Bonus.NEG),
    WarInvadingHeavyCavalryHitpoints(Category.WarWeapon, R.string.InvadingHeavyCavalryHitpoints, Bonus.NEG),
    WarWallSapperDamage(Category.WarWeapon, R.string.WallSapperDamage, Bonus.POS),
    WarInvadingFighterHitpoints(Category.WarWeapon, R.string.InvadingFighterHitpoints, Bonus.NEG),
    WarMortarTroopDamage(Category.WarWeapon, R.string.MortarTroopDamage, Bonus.POS),
    WarInvadingBomberHitpoints(Category.WarWeapon, R.string.InvadingBomberHitpoints, Bonus.POS),
    WarArmoredCarDamage(Category.WarWeapon, R.string.ArmoredCarDamage, Bonus.POS),
    WarRangedInfantryDamage(Category.WarWeapon, R.string.RangedInfantryDamage, Bonus.POS),
    WarSupplyVehicleHealing(Category.WarWeapon, R.string.SupplyVehicleHealing, Bonus.POS),
    WarInvadingBazookaHitpoints(Category.WarWeapon, R.string.InvadingBazookaHitpoints, Bonus.NEG),
    WarInvadingMRLHitpoints(Category.WarWeapon, R.string.InvadingMRLHitpoints, Bonus.NEG),
    WarAttackHelicoptersDamage(Category.WarWeapon, R.string.AttackHelicoptersDamage, Bonus.POS),
    WarParatroopersFromTransportsDamage(Category.WarWeapon, R.string.ParatroopersFromTransportsDamage, Bonus.POS),
    WarInvadingAPCHitpoints(Category.WarWeapon, R.string.InvadingAPCHitpoints, Bonus.NEG),
    WarBomberDamage(Category.WarWeapon, R.string.BomberDamage, Bonus.POS),
    WarInvadingMortarTroopHitpoints(Category.WarWeapon, R.string.InvadingMortarTroopHitpoints, Bonus.NEG),
    WarInvadingMachineGunInfantryHitpoints(Category.WarWeapon, R.string.InvadingMachineGunInfantryHitpoints, Bonus.NEG),
    WarInvadingHeavyInfantryHitpoints(Category.WarWeapon, R.string.InvadingHeavyInfantryHitpoints, Bonus.NEG),
    WarInvadingSupplyVehicleHitpoints(Category.WarWeapon, R.string.InvadingSupplyVehicleHitpoints, Bonus.NEG),
    WarInvadingRaiderHitpoints(Category.WarWeapon, R.string.InvadingRaiderHitpoints, Bonus.NEG),
    WarHeavyCavalryDamage(Category.WarWeapon, R.string.HeavyCavalryDamage, Bonus.POS),
    WarRaiderDamage(Category.WarWeapon, R.string.RaiderDamage, Bonus.POS),
    WarMRLDamage(Category.WarWeapon, R.string.MRLDamage, Bonus.POS),
    WarInvadingTacticalHelicopterHitpoints(Category.WarWeapon, R.string.InvadingTacticalHelicopterHitpoints, Bonus.NEG),
    WarRangedSiegeDamage(Category.WarWeapon, R.string.RangedSiegeDamage, Bonus.POS),

    WarRangedInfantryHitpoints(Category.WarArmor, R.string.RangedInfantryHitpoints, Bonus.POS),
    WarInvadingGeneralsDamage(Category.WarArmor, R.string.InvadingGeneralsDamage, Bonus.NEG),
    WarInvadingBazookaDamage(Category.WarArmor, R.string.InvadingBazookaDamage, Bonus.NEG),
    WarInvadingArmoredCarDamage(Category.WarArmor, R.string.InvadingArmoredCarDamage, Bonus.NEG),
    WarMortarTroopHitpoints(Category.WarArmor, R.string.MortarTroopHitpoints, Bonus.POS),
    WarInvadingHeavyInfantryDamage(Category.WarArmor, R.string.InvadingHeavyInfantryDamage, Bonus.NEG),
    WarHeavyCavalryHitpoints(Category.WarArmor, R.string.HeavyCavalryHitpoints, Bonus.POS),
    WarHeavyTankHitpoints(Category.WarArmor, R.string.HeavyTankHitpoints, Bonus.POS),
    WarAttackHelicoptersHitpoints(Category.WarArmor, R.string.AttackHelicoptersHitpoints, Bonus.POS),
    WarInvadingFighterDamage(Category.WarArmor, R.string.InvadingFighterDamage, Bonus.NEG),
    WarParatroopersFromTransportsHitpoints(Category.WarArmor, R.string.ParatroopersFromTransportsHitpoints, Bonus.POS),
    WarInvadingBomberDamage(Category.WarArmor, R.string.InvadingBomberDamage, Bonus.NEG),
    WarInvadingAttackHelicoptersDamage(Category.WarArmor, R.string.InvadingAttackHelicoptersDamage, Bonus.NEG),
    WarWallSapperHitpoints(Category.WarArmor, R.string.WallSapperHitpoints, Bonus.POS),
    WarBazookaHitpoints(Category.WarArmor, R.string.BazookaHitpoints, Bonus.POS),
    WarInvadingRaiderDamage(Category.WarArmor, R.string.InvadingRaiderDamage, Bonus.NEG),
    WarRaiderHitpoints(Category.WarArmor, R.string.RaiderHitpoints, Bonus.POS),
    WarGeneralsHitpoints(Category.WarArmor, R.string.GeneralsHitpoints, Bonus.POS),
    WarMachineGunInfantryHitpoints(Category.WarArmor, R.string.MachineGunInfantryHitpoints, Bonus.POS),
    WarArmoredCarHitpoints(Category.WarArmor, R.string.ArmoredCarHitpoints, Bonus.POS),
    WarInvadingMachineGunInfantryDamage(Category.WarArmor, R.string.InvadingMachineGunInfantryDamage, Bonus.NEG),
    WarInvadingGuerrillaDamage(Category.WarArmor, R.string.InvadingGuerrillaDamage, Bonus.NEG),
    WarInvadingAttackHelicoptersHitpoints(Category.WarWeapon, R.string.InvadingAttackHelicoptersHitpoints, Bonus.NEG),
    WarSupplyVehicleHitpoints(Category.WarArmor, R.string.SupplyVehicleHitpoints, Bonus.POS),
    WarInvadingAPCDamage(Category.WarArmor, R.string.InvadingAPCDamage, Bonus.NEG),
    WarMachineGunInfantryDamage(Category.WarWeapon, R.string.MachineGunInfantryDamage, Bonus.POS),
    WarHeavyInfantryHitpoints(Category.WarArmor, R.string.HeavyInfantryHitpoints, Bonus.POS),
    WarInvadingMRLDamage(Category.WarArmor, R.string.InvadingMRLDamage, Bonus.NEG),
    WarAPCHitpoints(Category.WarArmor, R.string.APCHitpoints, Bonus.POS),
    WarGuerrillaHitpoints(Category.WarArmor, R.string.GuerrillaHitpoints, Bonus.POS),
    WarInvadingSupplyVehicleHealing(Category.WarArmor, R.string.InvadingSupplyVehicleHealing, Bonus.NEG),
    WarInvadingHeavyCavalryDamage(Category.WarArmor, R.string.InvadingHeavyCavalryDamage, Bonus.NEG),
    WarInvadingRangedInfantryHitpoints(Category.WarWeapon, R.string.InvadingRangedInfantryHitpoints, Bonus.NEG),
    WarTacticalHelicopterHealing(Category.WarWeapon, R.string.TacticalHelicopterHealing, Bonus.POS),
    WarInvadingArmoredCarHitpoints(Category.WarWeapon, R.string.InvadingArmoredCarHitpoints, Bonus.NEG),
    WarHeavyInfantryDamage(Category.WarWeapon, R.string.HeavyInfantryDamage, Bonus.POS),
    WarInvadingRangedInfantryDamage(Category.WarArmor, R.string.InvadingRangedInfantryDamage, Bonus.NEG),
    WarInvadingParatroopersFromTransportsDamage(Category.WarArmor, R.string.InvadingParatroopersFromTransportsDamage, Bonus.NEG),
    WarBomberHitpoints(Category.WarArmor, R.string.BomberHitpoints, Bonus.POS),
    WarRangedSiegeHitpoints(Category.WarArmor, R.string.RangedSiegeHitpoints, Bonus.POS),
    WarTacticalHelicopterHitpoints(Category.WarArmor, R.string.TacticalHelicopterHitpoints, Bonus.POS),
    WarFighterHitpoints(Category.WarArmor, R.string.FighterHitpoints, Bonus.POS),
    WarMRLHitpoints(Category.WarArmor, R.string.MRLHitpoints, Bonus.POS),
    WarInvadingMortarTroopDamage(Category.WarArmor, R.string.InvadingMortarTroopDamage, Bonus.NEG),
    WarInvadingRangedSiegeDamage(Category.WarArmor, R.string.InvadingRangedSiegeDamage, Bonus.NEG),
    WarInvadingHeavyTankDamage(Category.WarArmor, R.string.InvadingHeavyTankDamage, Bonus.NEG),

    WarRedoubtDamage(Category.WarEquipment, R.string.RedoubtDamage, Bonus.POS),
    WarDefenderDamage(Category.WarEquipment, R.string.DefenderDamage, Bonus.POS),
    WarDefenderHitpoints(Category.WarEquipment, R.string.DefenderHitpoints, Bonus.POS),
    WarAllEnemyDefensiveTowersHitpoints(Category.WarEquipment, R.string.AllEnemyDefensiveTowersHitpoints, Bonus.NEG),
    WarAllDefensiveTowersHitpoints(Category.WarEquipment, R.string.AllDefensiveTowersHitpoints, Bonus.POS),
    WarAllEnemyDefensiveTowersDamage(Category.WarEquipment, R.string.AllEnemyDefensiveTowersDamage, Bonus.NEG),
    WarAllDefensiveTowersDamage(Category.WarEquipment, R.string.AllDefensiveTowersDamage, Bonus.POS),
    WarGeneralsDamage(Category.WarEquipment, R.string.GeneralsDamage, Bonus.POS),
    WarMissileSiloHitpoints(Category.WarEquipment, R.string.MissileSiloHitpoints, Bonus.POS),
    WarCatapultDamage(Category.WarEquipment, R.string.CatapultDamage, Bonus.POS),
    WarDefenderSpawnTime(Category.WarEquipment, R.string.DefenderSpawnTime, Bonus.NEG),
    WarEnemyAntiTankGunDamage(Category.WarEquipment, R.string.EnemyAntiTankGunDamage, Bonus.NEG),
    WarSniperTowerDamage(Category.WarEquipment, R.string.SniperTowerDamage, Bonus.POS),
    WarEnemyTowerHitpoints(Category.WarEquipment, R.string.EnemyTowerHitpoints, Bonus.NEG),
    WarEnemyDefenderSpawnTime(Category.WarEquipment, R.string.EnemyDefenderSpawnTime, Bonus.POS),
    WarEnemyTowerDamage(Category.WarEquipment, R.string.EnemyTowerDamage, Bonus.NEG),
    WarEnemyCatapultDamage(Category.WarEquipment, R.string.EnemyCatapultDamage, Bonus.NEG),
    WarTowerHitpoints(Category.WarEquipment, R.string.TowerHitpoints, Bonus.POS),
    WarEnemySniperTowerDamage(Category.WarEquipment, R.string.EnemySniperTowerDamage, Bonus.NEG),
    WarSniperTowerHitpoints(Category.WarEquipment, R.string.SniperTowerHitpoints, Bonus.POS),
    WarTowerDamage(Category.WarEquipment, R.string.TowerDamage, Bonus.POS),
    WarEnemyMissileSiloHitpoints(Category.WarEquipment, R.string.EnemyMissileSiloHitpoints, Bonus.NEG),
    WarAntiTankGunDamage(Category.WarEquipment, R.string.AntiTankGunDamage, Bonus.POS),
    WarRedoubtHitpoints(Category.WarEquipment, R.string.RedoubtHitpoints, Bonus.POS),
    WarAntiTankGunHitpoints(Category.WarEquipment, R.string.AntiTankGunHitpoints, Bonus.POS),
    WarInvadingTacticalHelicopterHealing(Category.WarArmor, R.string.InvadingTacticalHelicopterHealing, Bonus.NEG),
    WarCatapultHitpoints(Category.WarEquipment, R.string.CatapultHitpoints, Bonus.POS),
    WarEnemyRedoubtDamage(Category.WarEquipment, R.string.EnemyRedoubtDamage, Bonus.NEG),
    WarInvadingGeneralsHitpoints(Category.WarEquipment, R.string.InvadingGeneralsHitpoints, Bonus.NEG),
    WarEnemyAirDefenseDamage(Category.WarEquipment, R.string.EnemyAirDefenseDamage, Bonus.NEG),
    WarAirDefenseHitpoints(Category.WarEquipment, R.string.AirDefenseHitpoints, Bonus.POS),
    WarEnemyRedoubtHitpoints(Category.WarEquipment, R.string.EnemyRedoubtHitpoints, Bonus.NEG),
    WarMissileSiloDamage(Category.WarEquipment, R.string.MissileSiloDamage, Bonus.POS),
    WarEnemyMissileSiloDamage(Category.WarEquipment, R.string.EnemyMissileSiloDamage, Bonus.NEG),
    WarAirDefenseDamage(Category.WarEquipment, R.string.AirDefenseDamage, Bonus.POS),
    WarEnemyAirDefenseHitpoints(Category.WarEquipment, R.string.EnemyAirDefenseHitpoints, Bonus.NEG),
    WarEnemyCatapultHitpoints(Category.WarEquipment, R.string.EnemyCatapultHitpoints, Bonus.NEG),
    WarEnemySniperTowerHitpoints(Category.WarEquipment, R.string.EnemySniperTowerHitpoints, Bonus.NEG),
    WarEnemyAntiTankGunHitpoints(Category.WarEquipment, R.string.EnemyAntiTankGunHitpoints, Bonus.NEG),

    UNDEFINED(Category.UNDEFINED, R.array.array_categories, Bonus.POS);

    private final Category category;
    private final int resId;
    private final Bonus bonus;

    Skill(Category category, int resId, Bonus bonus) {
        this.category = category;
        this.resId = resId;
        this.bonus = bonus;
    }

    public Category getCategory() {
        return category;
    }

    public int getResId() {
        return resId;
    }

    public Bonus getBonus() {
        return bonus;
    }

}
